---
kind: pipeline
name: test

platform:
  os: linux
  arch: amd64

steps:
- name: lint
  image: koalaman/shellcheck-alpine:stable
  commands:
  - shellcheck ./wait-for

- name: test
  image: bats/bats
  commands:
  - bats ./wait-for.bats

image_pull_secrets:
- docker_config

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

---
kind: pipeline
name: build-package

platform:
  os: linux
  arch: amd64

steps:
- name: checksum
  image: alpine
  commands:
  - sha256sum wait-for > sha256sum.txt

- name: publish-github
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
    - wait-for
    - sha256sum.txt
    note: CHANGELOG.md
    overwrite: true
    title: ${DRONE_TAG}
  when:
    ref:
    - refs/tags/**

image_pull_secrets:
- docker_config

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

depends_on:
- test

---
kind: pipeline
name: build-container-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: dryrun
  image: plugins/docker:19
  settings:
    config:
      from_secret: docker_config
    dockerfile: docker/Dockerfile
    dry_run: true
    password:
      from_secret: docker_password
    repo: thegeeklab/${DRONE_REPO_NAME}
    username:
      from_secret: docker_username
  when:
    ref:
    - refs/pull/**

- name: publish-dockerhub
  image: plugins/docker:19
  settings:
    auto_tag: true
    auto_tag_suffix: amd64
    config:
      from_secret: docker_config
    dockerfile: docker/Dockerfile
    password:
      from_secret: docker_password
    repo: thegeeklab/${DRONE_REPO_NAME}
    username:
      from_secret: docker_username
  when:
    ref:
    - refs/heads/master
    - refs/tags/**

- name: publish-quay
  image: plugins/docker:19
  settings:
    auto_tag: true
    auto_tag_suffix: amd64
    config:
      from_secret: docker_config
    dockerfile: docker/Dockerfile
    password:
      from_secret: quay_password
    registry: quay.io
    repo: quay.io/thegeeklab/${DRONE_REPO_NAME}
    username:
      from_secret: quay_username
  when:
    ref:
    - refs/heads/master
    - refs/tags/**

image_pull_secrets:
- docker_config

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

depends_on:
- test

---
kind: pipeline
name: build-container-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: dryrun
  image: plugins/docker:19
  settings:
    config:
      from_secret: docker_config
    dockerfile: docker/Dockerfile
    dry_run: true
    password:
      from_secret: docker_password
    repo: thegeeklab/${DRONE_REPO_NAME}
    username:
      from_secret: docker_username
  when:
    ref:
    - refs/pull/**

- name: publish-dockerhub
  image: plugins/docker:19
  settings:
    auto_tag: true
    auto_tag_suffix: arm64
    config:
      from_secret: docker_config
    dockerfile: docker/Dockerfile
    password:
      from_secret: docker_password
    repo: thegeeklab/${DRONE_REPO_NAME}
    username:
      from_secret: docker_username
  when:
    ref:
    - refs/heads/master
    - refs/tags/**

- name: publish-quay
  image: plugins/docker:19
  settings:
    auto_tag: true
    auto_tag_suffix: arm64
    config:
      from_secret: docker_config
    dockerfile: docker/Dockerfile
    password:
      from_secret: quay_password
    registry: quay.io
    repo: quay.io/thegeeklab/${DRONE_REPO_NAME}
    username:
      from_secret: quay_username
  when:
    ref:
    - refs/heads/master
    - refs/tags/**

image_pull_secrets:
- docker_config

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

depends_on:
- test

---
kind: pipeline
name: build-container-arm

platform:
  os: linux
  arch: arm

steps:
- name: dryrun
  image: plugins/docker:19
  settings:
    config:
      from_secret: docker_config
    dockerfile: docker/Dockerfile
    dry_run: true
    password:
      from_secret: docker_password
    repo: thegeeklab/${DRONE_REPO_NAME}
    username:
      from_secret: docker_username
  when:
    ref:
    - refs/pull/**

- name: publish-dockerhub
  image: plugins/docker:19
  settings:
    auto_tag: true
    auto_tag_suffix: arm
    config:
      from_secret: docker_config
    dockerfile: docker/Dockerfile
    password:
      from_secret: docker_password
    repo: thegeeklab/${DRONE_REPO_NAME}
    username:
      from_secret: docker_username
  when:
    ref:
    - refs/heads/master
    - refs/tags/**

- name: publish-quay
  image: plugins/docker:19
  settings:
    auto_tag: true
    auto_tag_suffix: arm
    config:
      from_secret: docker_config
    dockerfile: docker/Dockerfile
    password:
      from_secret: quay_password
    registry: quay.io
    repo: quay.io/thegeeklab/${DRONE_REPO_NAME}
    username:
      from_secret: quay_username
  when:
    ref:
    - refs/heads/master
    - refs/tags/**

image_pull_secrets:
- docker_config

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

depends_on:
- test

---
kind: pipeline
name: notifications

platform:
  os: linux
  arch: amd64

steps:
- name: manifest-dockerhub
  image: plugins/manifest
  settings:
    auto_tag: true
    ignore_missing: true
    password:
      from_secret: docker_password
    spec: docker/manifest.tmpl
    username:
      from_secret: docker_username
  when:
    status:
    - success

- name: manifest-quay
  image: plugins/manifest
  settings:
    auto_tag: true
    ignore_missing: true
    password:
      from_secret: quay_password
    spec: docker/manifest-quay.tmpl
    username:
      from_secret: quay_username
  when:
    status:
    - success

- name: pushrm-dockerhub
  pull: always
  image: chko/docker-pushrm:1
  environment:
    DOCKER_PASS:
      from_secret: docker_password
    DOCKER_USER:
      from_secret: docker_username
    PUSHRM_FILE: README.md
    PUSHRM_SHORT: Poor-mans docker service synchronizer
    PUSHRM_TARGET: thegeeklab/${DRONE_REPO_NAME}
  when:
    status:
    - success

- name: pushrm-quay
  pull: always
  image: chko/docker-pushrm:1
  environment:
    APIKEY__QUAY_IO:
      from_secret: quay_token
    PUSHRM_FILE: README.md
    PUSHRM_TARGET: quay.io/thegeeklab/${DRONE_REPO_NAME}
  when:
    status:
    - success

- name: matrix
  image: plugins/matrix
  settings:
    homeserver:
      from_secret: matrix_homeserver
    password:
      from_secret: matrix_password
    roomid:
      from_secret: matrix_roomid
    template: "Status: **{{ build.status }}**<br/> Build: [{{ repo.Owner }}/{{ repo.Name }}]({{ build.link }}) ({{ build.branch }}) by {{ build.author }}<br/> Message: {{ build.message }}"
    username:
      from_secret: matrix_username
  when:
    status:
    - success
    - failure

image_pull_secrets:
- docker_config

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  status:
  - success
  - failure

depends_on:
- build-container-amd64
- build-container-arm
- build-container-arm64

---
kind: signature
hmac: cd3964127ba23a4f794b0ed48cbe2cef784c69e01837bccfaad4337a78f03664

...
