FROM arm64v8/alpine:3.13@sha256:071fa5de01a240dbef5be09d69f8fef2f89d68445d9175393773ee389b6f5935

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="wait-for"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/wait-for"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/wait-for"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/wait-for"

ADD wait-for /usr/local/bin/wait-for

RUN apk --no-cache add netcat-openbsd

USER root
CMD []
ENTRYPOINT ["/usr/local/bin/wait-for"]
