FROM arm32v7/alpine:3.15@sha256:dc18010aabc13ce121123c7bb0f4dcb6879ce22b4f7c65669a2c634b5ceecafb

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="wait-for"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/wait-for"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/wait-for"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/wait-for"

ADD wait-for /usr/local/bin/wait-for

RUN apk --no-cache add netcat-openbsd

USER root
CMD []
ENTRYPOINT ["/usr/local/bin/wait-for"]
