FROM alpine:3.15@sha256:ceeae2849a425ef1a7e591d8288f1a58cdf1f4e8d9da7510e29ea829e61cf512

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="wait-for"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/wait-for"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/wait-for"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/wait-for"

ADD wait-for /usr/local/bin/wait-for

RUN apk --no-cache add netcat-openbsd

USER root
CMD []
ENTRYPOINT ["/usr/local/bin/wait-for"]
