---
when:
  - event: [pull_request, tag]
  - event: [push, manual]
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

steps:
  - name: pushrm-dockerhub
    image: docker.io/chko/docker-pushrm:1
    depends_on: []
    environment:
      DOCKER_PASS:
        from_secret: docker_password
      DOCKER_USER:
        from_secret: docker_username
      PUSHRM_FILE: README.md
      PUSHRM_SHORT: Retry any shell command
      PUSHRM_TARGET: ${CI_REPO}
    when:
      - event: [push, manual]
        branch:
          - ${CI_REPO_DEFAULT_BRANCH}
        status: [success]

  - name: pushrm-quay
    image: docker.io/chko/docker-pushrm:1
    depends_on: []
    environment:
      APIKEY__QUAY_IO:
        from_secret: quay_token
      PUSHRM_FILE: README.md
      PUSHRM_TARGET: quay.io/${CI_REPO}
    when:
      - event: [push, manual]
        branch:
          - ${CI_REPO_DEFAULT_BRANCH}
        status: [success]

depends_on:
  - build-package
  - build-container
