---
when:
  - event: [pull_request, tag]
  - event: [push, manual]
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

steps:
  - name: markdownlint
    image: quay.io/thegeeklab/markdownlint-cli
    depends_on: []
    commands:
      - markdownlint 'README.md' 'CONTRIBUTING.md'

  - name: spellcheck
    image: ghcr.io/streetsidesoftware/cspell
    depends_on: []
    commands:
      - cspell-cli lint . --gitignore --color

  - name: link-validation
    image: docker.io/lycheeverse/lychee
    depends_on: []
    commands:
      - lychee --no-progress --format detailed README.md
    environment:
      GITHUB_TOKEN:
        from_secret: github_token_ro
