---
when:
  - event: [pull_request, tag]
  - event: [push, manual]
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

steps:
  - name: lint
    image: docker.io/koalaman/shellcheck-alpine:stable
    depends_on: []
    commands:
      - shellcheck ./wait-for

  - name: test-ncat
    image: docker.io/bats/bats
    depends_on: []
    commands:
      - bats ./wait-for.bats

  - name: test-bash
    image: docker.io/bats/bats
    depends_on: []
    commands:
      - rm -rf /usr/bin/nc
      - bats ./wait-for.bats
